---
- name: Reload initd
  command: initctl reload-configuration

- name: Restart kafka service also daemon-reload to pick up config changes
  systemd:
    name: kafka
    state: restarted
    daemon_reload: yes
